In [1]:
#Q1.5 One Away
def oneaway(s1, s2):
    l1 = len(s1)
    l2 = len(s2)
    if abs(l1 - l2) > 1: return False
    if l1 > l2: 
        longstr = s1
        shortstr = s2
    elif l2 > l1:
        longstr = s2
        shortstr = s1
    else:
        longstr = s1
        shortstr = s2
    difference = False
    shortidx = 0
    step = 1 - abs(l1 - l2)
    for l in longstr:
        if l != shortstr[shortidx]:
            if difference == True: 
                return False
            else:
                difference = True
                shortidx += step
        else:
            shortidx += 1
            if shortidx == len(shortstr): break
    return True

In [9]:
s1 = 'pale'
s2 = 'palle'
s3 = 'bale'
s4 = 'pales'
s5 = 'pareo'
print(oneaway(s1,s2))
print(oneaway(s1,s3))
print(oneaway(s1,s4))
print(oneaway(s1,s5))

True
True
True
False


In [68]:
from math import floor
import numpy as np
from copy import copy
#Q1.7 def rotatematrix
"""trying to do this by moving entire rows is more difficult than just replacing index by index
"""
def rotate_matrix(mat):
    start = 0
    end = len(mat) - 1
    for layer in range(floor(len(mat)/2)):
        end = len(mat) - 1 - layer
        for i in range(layer, end):
            #this ensures the end for inner layers you can still walk through the bottom and left sides
            #correctly i will automatically index the correct value in top and right, whereas b and l
            #we need to walk from the end to the start+1 so subtract 0,1,2,... from the end index
            #this offset ensures firsti:offset=0, second:offset=1 a count would do the same thing but clearer
            offset = i - layer 
            print(offset)
            temp = mat[layer, i]
            mat[layer, i] = mat[end-offset, layer] #left -> top
            mat[end-offset, layer] = mat[end, end-offset] #bottom -> left
            mat[end, end-offset] = mat[i, end] #right -> bottom
            mat[i, end] = temp #top -> right
    return mat

In [69]:
a1 = np.arange(25).reshape((5,5))
a2 = np.arange(16).reshape((4,4))
print(a1)
rotate_matrix(a1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
0
1
2
3
0
1


array([[20, 15, 10,  5,  0],
       [21, 16, 11,  6,  1],
       [22, 17, 12,  7,  2],
       [23, 18, 13,  8,  3],
       [24, 19, 14,  9,  4]])